version: '3.4'

services:
  
  productdb:
    container_name: productdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=productDb
    restart: always
    ports:
      - "5435:5432"
    volumes:
      - 19e47da99d101ebdfb6ef2a70a9ccc52db3f88b2d9aeb4e5bb05ca897eec3317:/var/lib/postgresql/data/
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5070:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  products.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "10000:80"
    depends_on:
      - productdb
